name: Docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/docker.yml
      - git-sync/**
      - .dockerignore
      - Dockerfile
    tags:
      - v*
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        default: false

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up qemu
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: get image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/therealm-tech/git-sync
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: log in to registry
        if: ${{ startsWith(github.ref, 'refs/tags/v') || inputs.push }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/v') || inputs.push == true }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
